name: Test vars action
on:
  workflow_dispatch:

jobs:
  tag:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: test vars action
      uses: ./.github/actions/whatver
    